services:
  - type: web
    name: telegram-ai-bot
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: "python3 main.py"
